In [ ]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv(r"IMDB Dataset.csv")

In [ ]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [ ]:
!pip install requests pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import nltk

resources = ['punkt', 'punkt_tab', 'stopwords', 'wordnet']

for r in resources:
    nltk.download(r)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [ ]:
!pip install nltk emoji beautifulsoup4 textblob

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: emoji in /usr/local/lib/python3.12/dist-packages (2.15.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

Import Required Libraries

In [ ]:
import re
import nltk
import emoji
from bs4 import BeautifulSoup
from textblob import TextBlob

Download NLTK resources

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

Lowercasing(FIRST CLEANING STEP)

In [ ]:
def lowercase(text):
  return text.lower()

In [ ]:
lowercase(df['review'][0])

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Remove HTML Tag

In [ ]:
def remove_html(text):
  soup = BeautifulSoup(text, "html.parser")
  return soup.get_text()

In [ ]:
remove_html(df['review'][0])

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Remove URLs

In [ ]:
def remove_urls(text):
  return re.sub(r'http\S+|www\S+', '', text)

In [ ]:
remove_urls(df['review'][0])

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Remove Emojis

In [ ]:
def remove_emojis(text):
  return emoji.replace_emoji(text, replace='')

Step 8:Chat Word Treatment

In [ ]:
import requests

url = "https://raw.githubusercontent.com/rishabhverma17/sms_slang_translator/master/slang.txt"
response = requests.get(url)

with open("chat_words.txt", "w") as f:
    f.write(response.text)

In [ ]:
chat_words = {}

with open("chat_words.txt", "r") as f:
    for line in f:
        if "=" in line:
            key, value = line.strip().split("=")
            chat_words[key.lower()] = value.lower()

chat_words

{'a3': 'anytime, anywhere, anyplace',
 'adih': 'another day in hell',
 'afk': 'away from keyboard',
 'afaik': 'as far as i know',
 'asap': 'as soon as possible',
 'asl': 'age, sex, location',
 'atk': 'at the keyboard',
 'atm': 'at the moment',
 'bae': 'before anyone else',
 'bak': 'back at keyboard',
 'bbl': 'be back later',
 'bbs': 'be back soon',
 'bfn': 'bye for now',
 'b4n': 'bye for now',
 'brb': 'be right back',
 'bruh': 'bro',
 'brt': 'be right there',
 'bsaaw': 'big smile and a wink',
 'btw': 'by the way',
 'bwl': 'bursting with laughter',
 'csl': 'can’t stop laughing',
 'cu': 'see you',
 'cul8r': 'see you later',
 'cya': 'see you',
 'dm': 'direct message',
 'faq': 'frequently asked questions',
 'fc': 'fingers crossed',
 'fimh': 'forever in my heart',
 'fomo': 'fear of missing out',
 'fr': 'for real',
 'fwiw': "for what it's worth",
 'fyp': 'for you page',
 'fyi': 'for your information',
 'g9': 'genius',
 'gal': 'get a life',
 'gg': 'good game',
 'gmta': 'great minds think alike',
 'gn': 'good night',
 'goat': 'greatest of all time',
 'gr8': 'great!',
 'hbd': 'happy birthday',
 'ic': 'i see',
 'icq': 'i seek you',
 'idc': 'i don’t care',
 'idk': "i don't know",
 'ifyp': 'i feel your pain',
 'ilu': 'i love you',
 'ily': 'i love you',
 'imho': 'in my honest/humble opinion',
 'imu': 'i miss you',
 'imo': 'in my opinion',
 'iow': 'in other words',
 'irl': 'in real life',
 'iykyk': 'if you know, you know',
 'jk': 'just kidding',
 'kiss': 'keep it simple, stupid',
 'l': 'loss',
 'l8r': 'later',
 'ldr': 'long distance relationship',
 'lmk': 'let me know',
 'lmao': 'laughing my a** off',
 'lol': 'laughing out loud',
 'ltns': 'long time no see',
 'm8': 'mate',
 'mfw': 'my face when',
 'mid': 'mediocre',
 'mrw': 'my reaction when',
 'mte': 'my thoughts exactly',
 'nvm': 'never mind',
 'nrn': 'no reply necessary',
 'npc': 'non-player character',
 'oic': 'oh i see',
 'op': 'overpowered',
 'pita': 'pain in the a**',
 'pov': 'point of view',
 'prt': 'party',
 'prw': 'parents are watching',
 'rofl': 'rolling on the floor laughing',
 'roflol': 'rolling on the floor laughing out loud',
 'rotflmao': 'rolling on the floor laughing my a** off',
 'rn': 'right now',
 'sk8': 'skate',
 'stats': 'your sex and age',
 'sus': 'suspicious',
 'tbh': 'to be honest',
 'tfw': 'that feeling when',
 'thx': 'thank you',
 'time': 'tears in my eyes',
 'tldr': 'too long, didn’t read',
 'tntl': 'trying not to laugh',
 'ttfn': 'ta-ta for now!',
 'ttyl': 'talk to you later',
 'u': 'you',
 'u2': 'you too',
 'u4e': 'yours for ever',
 'w': 'win',
 'w8': 'wait...',
 'wb': 'welcome back',
 'wtf': 'what the f**k',
 'wtg': 'way to go!',
 'wuf': 'where are you from?',
 'wyd': 'what you doing?',
 'wywh': 'wish you were here',
 'zzz': 'sleeping, bored, tired'}

In [ ]:
def chat_word_treatment(text):
    words = text.split()
    return " ".join(chat_words.get(word, word) for word in words)

In [ ]:
df['chatword_test'] = df['review'].apply(chat_word_treatment)
df[['review', 'chatword_test']].head()

,review,chatword_test
0,One of the other reviewers has mentioned that ...,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,A wonderful little production. <br /><br />The...
2,I thought this was a wonderful way to spend ti...,I thought this was a wonderful way to spend te...
3,Basically there's a family where a little boy ...,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...","Petter Mattei's ""Love in the Time of Money"" is..."

Remove Punctuation

In [ ]:
def remove_punctuation(text):
    return re.sub(r'[^\w\s]', '', text)

In [ ]:
remove_punctuation(df['review'][0])

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [ ]:
def spelling_correction(text):
    return str(TextBlob(text).correct())

Remove stop words

In [ ]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    return " ".join(word for word in words if word not in stop_words)

In [ ]:
remove_stopwords(df['review'][0])

"One reviewers mentioned watching 1 Oz episode hooked. They right, exactly happened me.<br /><br />The first thing struck Oz brutality unflinching scenes violence, set right word GO. Trust me, show faint hearted timid. This show pulls punches regards drugs, sex violence. Its hardcore, classic use word.<br /><br />It called OZ nickname given Oswald Maximum Security State Penitentary. It focuses mainly Emerald City, experimental section prison cells glass fronts face inwards, privacy high agenda. Em City home many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.<br /><br />I would say main appeal show due fact goes shows dare. Forget pretty pictures painted mainstream audiences, forget charm, forget romance...OZ mess around. The first episode I ever saw struck nasty surreal, I say I ready it, I watched more, I developed taste Oz, got accustomed high levels graphic violence. Not violence, injustice (crooked guards who'll sold nickel, inmates who'll kill order get away it, well mannered, middle class inmates turned prison bitches due lack street skills prison experience) Watching Oz, may become comfortable uncomfortable viewing....thats get touch darker side."

Tokenization

In [ ]:
from nltk.tokenize import word_tokenize

def tokenize(text):
    return word_tokenize(text)

In [ ]:
tokenize(df['review'][0])

['One',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'Oz',
 'episode',
 'you',
 "'ll",
 'be',
 'hooked',
 '.',
 'They',
 'are',
 'right',
 ',',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'me.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'The',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'Oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 ',',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'GO',
 '.',
 'Trust',
 'me',
 ',',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 '.',
 'This',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 ',',
 'sex',
 'or',
 'violence',
 '.',
 'Its',
 'is',
 'hardcore',
 ',',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'word.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'It',
 'is',
 'called',
 'OZ',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 '.',
 'It',
 'focuses',
 'mainly',
 'on',
 'Emerald',
 'City',
 ',',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 ',',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 '.',
 'Em',
 'City',
 'is',
 'home',
 'to',
 'many',
 '..',
 'Aryans',
 ',',
 'Muslims',
 ',',
 'gangstas',
 ',',
 'Latinos',
 ',',
 'Christians',
 ',',
 'Italians',
 ',',
 'Irish',
 'and',
 'more',
 '....',
 'so',
 'scuffles',
 ',',
 'death',
 'stares',
 ',',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'away.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'I',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'would',
 "n't",
 'dare',
 '.',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 ',',
 'forget',
 'charm',
 ',',
 'forget',
 'romance',
 '...',
 'OZ',
 'does',
 "n't",
 'mess',
 'around',
 '.',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 ',',
 'I',
 'could',
 "n't",
 'say',
 'I',
 'was',
 'ready',
 'for',
 'it',
 ',',
 'but',
 'as',
 'I',
 'watched',
 'more',
 ',',
 'I',
 'developed',
 'a',
 'taste',
 'for',
 'Oz',
 ',',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 '.',
 'Not',
 'just',
 'violence',
 ',',
 'but',
 'injustice',
 '(',
 'crooked',
 'guards',
 'who',
 "'ll",
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 ',',
 'inmates',
 'who',
 "'ll",
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 ',',
 'well',
 'mannered',
 ',',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 ')',
 'Watching',
 'Oz',
 ',',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewing',
 '....',
 'thats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side',
 '.']

In [ ]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary
# Done above else see in TMDB_Dataset_Creation

In [ ]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

In [ ]:
text = " ".join(df['review'])

In [ ]:
words = text.split()

In [ ]:
total_words = len(words)
print("Total words:", total_words)

Total words: 11557847

In [ ]:
vocabulary = set(words)
print("Total unique words:", len(vocabulary))

Total unique words: 438729

In [ ]:
# Problem 3

# Apply One Hot Encoding

In [ ]:
# Import Library
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
one_hot = CountVectorizer(binary=True)

one_hot_matrix = one_hot.fit_transform(df['review'])

In [ ]:
one_hot_vocab = one_hot.get_feature_names_out()
print("One Hot Vocabulary size:", len(one_hot_vocab))

One Hot Vocabulary size: 101895

In [ ]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

In [ ]:
bow = CountVectorizer()

bow_matrix = bow.fit_transform(df['review'])

In [ ]:
bow_vocab = bow.get_feature_names_out()
print("Vocabulary size:", len(bow_vocab))

Vocabulary size: 101895

In [ ]:
word_counts = bow_matrix.sum(axis=0)

In [ ]:
word_freq = dict(zip(bow_vocab, word_counts.tolist()[0]))

# Print first 10 words
list(word_freq.items())[:10]

[('00', 208),
 ('000', 619),
 ('00000000000', 2),
 ('0000000000001', 1),
 ('00000001', 1),
 ('00001', 2),
 ('00015', 1),
 ('000dm', 1),
 ('000s', 1),
 ('001', 5)]

In [ ]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [ ]:
bigram = CountVectorizer(ngram_range=(2, 2))

bigram_matrix = bigram.fit_transform(df['review'])

In [ ]:
print("Bigram vocabulary size:", len(bigram.get_feature_names_out()))

Bigram vocabulary size: 2366111

Tri gram( 3 words together)

In [ ]:
trigram = CountVectorizer(ngram_range=(3, 3))

trigram_matrix = trigram.fit_transform(df['review'])

In [ ]:
print("Trigram vocabulary size:", len(trigram.get_feature_names_out()))

Observation
Unigram vocabulary  <  Bigram vocabulary  <  Trigram vocabulary

In [ ]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.